cleanup

diff --git a/scripts/update-deps b/scripts/update-deps
--- a/scripts/update-deps
+++ b/scripts/update-deps
@@ -1,7 +1,12 @@
 #!/usr/bin/env bash
 
-# always immediately exit upon error
-set -e
+#
+# Called with no arguments. Will prompt for confirmation.
+# Installs latest versions of all dependencies and updates their version numbers in
+# package.json. Will then commit package.json if there are any changes.
+#
+
+set -e # always immediately exit upon error
 
 scripts_dir="`dirname $0`"
 
@@ -11,16 +16,16 @@ read -p "Do you want to update all depedencies and commit changes in package.jso
 
 if [[ "$yn" != "y" ]]
 then
-    exit
+  exit
 fi
 
-npm update
+npm update # will modify package.json, but not commit
 
 if "$scripts_dir/require-clean-working-tree" 'package.json'
 then
-    echo 'No dependencies to update'
+  echo 'No dependencies to update'
 else
-    git add package.json
-    git commit -m 'update dependencies'
-    echo 'Updated dependencies'
+  git add package.json
+  git commit -m 'update dependencies'
+  echo 'Updated dependencies'
 fi
diff --git a/scripts/version b/scripts/version
--- a/scripts/version
+++ b/scripts/version
@@ -1,29 +1,38 @@
 #!/usr/bin/env bash
 
-# remaining args go to npm-version
+#
+# version <version-number>
+#
+# Generates all files for a release and commits them to a tagged "release commit",
+# which is detached from the current branch so it does not clutter the source files.
+# Calls `npm version` internally. Additional arguments are forwarded.
+#
 
-# always immediately exit upon error
-set -e
+set -e # always immediately exit upon error
 
 scripts_dir=`dirname $0`
 
 if [[ ! "$@" ]]
 then
-    echo 'You must supply a version argument'
-    exit 1
+  echo 'You must supply a version argument'
+  exit 1
 fi
 
 "$scripts_dir/require-clean-working-tree"
 "$scripts_dir/update-deps"
 
+# move away from the current branch (for committing release files)
 current_ref=`git symbolic-ref --quiet HEAD`
 git checkout --detach
 
+# will build the release and commit all generated files
+# see the version-related package.json scripts for more info
 if npm version "$@"
 then
-    echo 'Successfully built new version release'
+  echo 'Successfully built new version release'
 fi
 
-git symbolic-ref HEAD "$current_ref"
-git reset --quiet # unstage all release files
-git reset --hard # remove release files that are under vc (package.json)
+# return to the original branch, but maintain generated files
+git symbolic-ref HEAD "$current_ref" # will keep the diff staged
+git reset --quiet # unstage all generated files
+git reset --hard # revert files under version control (package.json)
